on: 
  push:
  workflow_dispatch:
jobs:
 build-tauri-ubuntu:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          shared-key: "ubuntu"
      - name: install dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: npm install
      - name: build tauri app
        run: npm run tauri build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: linux
            path: src-tauri/target/release/bundle/appimage/jpxs-launcher_0.1.0_amd64.AppImage
 build-tauri-windows:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          shared-key: "windows"
      - name: install frontend dependencies
        run: npm install
      - name: build tauri app
        run: npm run tauri build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: windows
            path: src-tauri\target\release\bundle\nsis\jpxs-launcher_0.1.0_x64-setup.exe
 build-tauri-mac:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
          shared-key: "mac"
      - name: install frontend dependencies
        run: npm install
      - name: build tauri app
        run: npm run tauri build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: mac
            path: src-tauri/target/release/bundle/macos/jpxs-launcher.app
